import { Post, Story, UserProfile, UserAccount, Conversation, AppNotification, ReelItem } from './types';

export const INITIAL_REELS: ReelItem[] = [
  {
    id: 'reel_1',
    videoPoster: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=800&auto=format&fit=crop',
    username: 'aurora_lens',
    userImg: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    caption: 'When the northern lights ignite the entire horizon 🌌✨ Turn audio on!',
    song: 'Ambient Dreams • Arctic Soundscapes',
    likes: 45200,
    comments: 1120,
    isLiked: false,
    isSaved: false,
    commentsList: [
      { id: '1', user: 'foodie_heaven', text: 'Spectacular long exposure!' },
      { id: '2', user: 'atelier_nord', text: 'Incredible chromatic harmony.' },
    ],
  },
  {
    id: 'reel_2',
    videoPoster: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop',
    username: 'foodie_heaven',
    userImg: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    caption: 'Wood-fired sourdough pizza pull in 4K 🍕🧀 Pure artisan craft.',
    song: 'Tarantella Vibes • Napoli Classics',
    likes: 19200,
    comments: 404,
    isLiked: false,
    isSaved: false,
    commentsList: [
      { id: '3', user: 'julian_vance', text: 'That blistered crust is perfection.' },
    ],
  },
  {
    id: 'reel_3',
    videoPoster: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    username: 'summit_views',
    userImg: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop',
    caption: 'Alpine morning above the cloud ceiling 🏔️🦅 Silence at 3,000 meters.',
    song: 'Ethereal Peaks • Ambient Strings',
    likes: 31400,
    comments: 672,
    isLiked: true,
    isSaved: true,
    commentsList: [
      { id: '4', user: 'aurora_lens', text: 'The atmosphere here is unreal.' },
    ],
  },
  {
    id: 'reel_4',
    videoPoster: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    username: 'atelier_nord',
    userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    caption: 'Natural oak, linen textures, and late afternoon shadows in Copenhagen ☕🌿',
    song: 'Nordic Minimalism • Piano Solo',
    likes: 14800,
    comments: 290,
    isLiked: false,
    isSaved: false,
    commentsList: [
      { id: '5', user: 'julian_vance', text: 'Timeless studio aesthetics.' },
    ],
  },
];

export const DEFAULT_ACCOUNTS: UserAccount[] = [
  {
    id: 'user_julian',
    username: 'julian_vance',
    fullName: 'Julian Vance',
    email: 'julian@snapgrid.studio',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    bio: 'Visual curator & editorial photographer. Exploring modern brutalism, spatial geometry, and silent daylight.',
    website: 'snapgrid.art/julian',
    postsCount: 14,
    followersCount: 3840,
    followingCount: 215,
    isVerified: true,
    streakDays: 7,
    curatorLevel: 'Master of Light',
    tags: ['#architecture', '#minimalism', '#editorial', '#brutalism'],
    joinedDate: 'Joined March 2026',
    savedPostIds: [102],
    likedPostIds: [102],
    followingUsernames: ['aurora_lens', 'atelier_nord'],
    friends: ['aurora_lens', 'atelier_nord'],
  },
  {
    id: 'user_aurora',
    username: 'aurora_lens',
    fullName: 'Astrid Lind',
    email: 'astrid@arcticframes.no',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    bio: 'Nordic expedition photographer. Documenting Arctic twilight, glaciers, and sub-zero minimalism.',
    website: 'astridlind.no',
    postsCount: 29,
    followersCount: 11400,
    followingCount: 180,
    isVerified: true,
    streakDays: 9,
    curatorLevel: 'Atmospheric Master',
    tags: ['#landscape', '#arctic', '#nordic', '#raw'],
    joinedDate: 'Joined January 2026',
    savedPostIds: [],
    likedPostIds: [101],
    followingUsernames: ['julian_vance', 'atelier_nord'],
    friends: ['julian_vance'],
  },
  {
    id: 'user_atelier',
    username: 'atelier_nord',
    fullName: 'Freja Olsen',
    email: 'freja@nordicstudio.dk',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    bio: 'Copenhagen interior architect and analog printmaker. Form, proportion, and quiet warmth.',
    website: 'ateliernord.dk',
    postsCount: 42,
    followersCount: 8900,
    followingCount: 340,
    isVerified: true,
    streakDays: 14,
    curatorLevel: 'Editorial Fellow',
    tags: ['#nordic', '#architecture', '#interiors', '#analog'],
    joinedDate: 'Joined February 2026',
    savedPostIds: [],
    likedPostIds: [],
    followingUsernames: ['julian_vance'],
    friends: ['julian_vance'],
  },
  {
    id: 'user_foodie',
    username: 'foodie_heaven',
    fullName: 'Lucas Rossi',
    email: 'lucas@rossiculinary.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    bio: 'Gastronomy visual arts. Capturing the organic beauty of culinary craftsmanship.',
    website: 'rossiculinary.com',
    postsCount: 26,
    followersCount: 7300,
    followingCount: 190,
    isVerified: true,
    streakDays: 5,
    curatorLevel: 'Artisan Curator',
    tags: ['#culinary', '#foodart', '#gastronomy', '#light'],
    joinedDate: 'Joined February 2026',
    savedPostIds: [],
    likedPostIds: [],
    followingUsernames: ['julian_vance'],
    friends: [],
  },
];

export const INITIAL_USER_PROFILE: UserProfile = DEFAULT_ACCOUNTS[0];

export const INITIAL_STORIES: Story[] = [
  {
    id: 's1',
    username: 'aurora_lens',
    userImg: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    mediaUrl: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    hasUnseen: true,
    timestamp: '1h ago',
  },
  {
    id: 's2',
    username: 'atelier_nord',
    userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    mediaUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    hasUnseen: true,
    timestamp: '3h ago',
  },
  {
    id: 's3',
    username: 'foodie_heaven',
    userImg: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    mediaUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    hasUnseen: false,
    timestamp: '5h ago',
  },
  {
    id: 's4',
    username: 'summit_views',
    userImg: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=200&auto=format&fit=crop',
    mediaUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    mediaType: 'image',
    hasUnseen: true,
    timestamp: '6h ago',
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 101,
    userId: 'user_aurora',
    username: 'aurora_lens',
    userImg: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    location: 'Lofoten Islands, Norway',
    postImg: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=1200&auto=format&fit=crop',
    caption: 'Fjord Shadows & Arctic Twilight. Long exposure captures the frozen emerald ribbons across the night sky. 🌌🏔️ #landscape #norway #arctic #fineart',
    likes: 1540,
    isLiked: false,
    isSaved: false,
    timestamp: '2 hours ago',
    isVerified: true,
    filter: 'none',
    exif: {
      camera: 'Sony A1',
      lens: 'FE 14mm f/1.8 GM',
      aperture: 'f/1.8',
      shutter: '15s',
      iso: 1600,
    },
    tags: ['#landscape', '#norway', '#arctic', '#aurora'],
    comments: [
      {
        id: 'c1',
        username: 'atelier_nord',
        userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
        text: 'The tonal range and deep midnight blues are magnificent!',
        timestamp: '1h ago',
        likes: 18,
      },
      {
        id: 'c2',
        username: 'julian_vance',
        userImg: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
        text: 'Clean composition with stunning natural light.',
        timestamp: '40m ago',
        likes: 12,
      },
    ],
  },
  {
    id: 102,
    userId: 'user_atelier',
    username: 'atelier_nord',
    userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    location: 'Copenhagen, Denmark',
    postImg: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1200&auto=format&fit=crop',
    caption: 'Form and Function. Natural oak, linen textures, and late afternoon shadows in the studio. ☕🌿 #nordicdesign #interiors #geometry',
    likes: 1120,
    isLiked: true,
    isSaved: true,
    timestamp: '5 hours ago',
    isVerified: true,
    filter: 'none',
    exif: {
      camera: 'Hasselblad 907X',
      lens: 'XCD 45mm f/4 P',
      aperture: 'f/5.6',
      shutter: '1/160s',
      iso: 64,
    },
    tags: ['#nordicdesign', '#interiors', '#stilllife', '#scandinavia'],
    comments: [
      {
        id: 'c3',
        username: 'foodie_heaven',
        userImg: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
        text: 'The subtle warmth and organic materials feel so grounded.',
        timestamp: '3h ago',
        likes: 9,
      },
    ],
  },
  {
    id: 103,
    userId: 'user_foodie',
    username: 'foodie_heaven',
    userImg: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    location: 'Trastevere, Rome',
    postImg: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1200&auto=format&fit=crop',
    caption: 'The Midnight Bistro. A study in lighting, warmth, and the geometry of an artisan wood-fired bake. 🍕✨ #foodart #culinary #ambient',
    likes: 640,
    isLiked: false,
    isSaved: false,
    timestamp: '8 hours ago',
    isVerified: true,
    filter: 'none',
    exif: {
      camera: 'Sony A7 IV',
      lens: 'FE 50mm f/1.2 GM',
      aperture: 'f/1.8',
      shutter: '1/250s',
      iso: 800,
    },
    tags: ['#foodart', '#culinary', '#night', '#bokeh'],
    comments: [],
  },
];

export const EXPLORE_GRID_ITEMS = [
  {
    id: 'e1',
    img: 'https://images.unsplash.com/photo-1549490349-8643362247b5?q=80&w=800&auto=format&fit=crop',
    title: 'Minimalist Interior',
    author: 'atelier_nord',
    likes: 1420,
    category: 'Architecture',
    exif: { camera: 'Leica SL2-S', lens: '24-70mm', aperture: 'f/2.8', shutter: '1/320s', iso: 200 },
  },
  {
    id: 'e2',
    img: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=800&auto=format&fit=crop',
    title: 'Aurora Horizon',
    author: 'aurora_lens',
    likes: 2450,
    category: 'Landscape',
    exif: { camera: 'Sony A1', lens: '14mm', aperture: 'f/1.8', shutter: '15s', iso: 1600 },
  },
  {
    id: 'e3',
    img: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800&auto=format&fit=crop',
    title: 'Abstract Form & Light',
    author: 'julian_vance',
    likes: 673,
    category: 'Minimalism',
    exif: { camera: 'Canon R5', lens: '50mm f/1.2', aperture: 'f/2.0', shutter: '1/800s', iso: 100 },
  },
  {
    id: 'e4',
    img: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop',
    title: 'Gastronomy Study',
    author: 'foodie_heaven',
    likes: 540,
    category: 'Culinary',
    exif: { camera: 'Sony A7 IV', lens: '50mm GM', aperture: 'f/1.8', shutter: '1/250s', iso: 800 },
  },
  {
    id: 'e5',
    img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    title: 'Alpine Vista',
    author: 'summit_views',
    likes: 2190,
    category: 'Travel',
    exif: { camera: 'Sony A1', lens: '70-200mm GM', aperture: 'f/4.0', shutter: '1/1600s', iso: 100 },
  },
  {
    id: 'e6',
    img: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    title: 'Glass Towers',
    author: 'atelier_nord',
    likes: 954,
    category: 'Architecture',
    exif: { camera: 'Fujifilm GFX 100', lens: '32-64mm', aperture: 'f/8.0', shutter: '1/200s', iso: 100 },
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    type: 'like',
    username: 'aurora_lens',
    userImg: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    postImg: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?q=80&w=200&auto=format&fit=crop',
    timeAgo: '15m ago',
    read: false,
  },
  {
    id: 'n2',
    type: 'comment',
    username: 'atelier_nord',
    userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    commentText: 'The geometry and soft daylight on this is phenomenal.',
    timeAgo: '45m ago',
    read: false,
  },
  {
    id: 'n3',
    type: 'follow',
    username: 'foodie_heaven',
    userImg: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop',
    timeAgo: '2h ago',
    read: true,
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    username: 'aurora_lens',
    fullName: 'Astrid Lind',
    userImg: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=400&auto=format&fit=crop',
    lastMessage: 'Welcome to Snap Grid! Feel free to share your shots or send shorts here.',
    timeAgo: '25m ago',
    unread: true,
    isFriend: true,
    messages: [
      {
        id: 'm1',
        sender: 'other',
        text: 'Welcome to Snap Grid! Feel free to share your shots or send shorts here.',
        timestamp: '10:30 AM',
      },
    ],
  },
  {
    id: 'conv2',
    username: 'atelier_nord',
    fullName: 'Freja Olsen',
    userImg: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=200&auto=format&fit=crop',
    lastMessage: 'Connected as friends! Feel free to exchange monographs.',
    timeAgo: '1h ago',
    unread: false,
    isFriend: true,
    messages: [
      {
        id: 'm2',
        sender: 'other',
        text: 'Connected as friends! Feel free to exchange monographs.',
        timestamp: '9:15 AM',
      },
    ],
  },
];
